cp delta/vision.html core/client/templates/.
cp delta/router.js core/lib/.
cp delta/layout.html core/client/templates/application/.
cp delta/paper.html core/client/templates/.
cp delta/c.js core/collections/.
cp delta/joinus.html core/client/templates/.
cp delta/people.js core/server/data/.
cp delta/dtr.html core/client/.
cp delta/dtr.css core/client/.
cp delta/projects.js core/server/data/.
cp delta/worth.js core/client/templates/.
